services:

  git-server:
    build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - ./ro-keys:/git-server/ro-keys
    - ./rw-keys:/git-server/rw-keys
    - ./repos:/git-server/repos

